"""Gunkel's divisions of ideonomy, recovered from ideonomy.mit.edu/division.html.

Each division is a binomen: THEME (the category of ideas treated) -> FIELD
(a name coined from Greek roots). Gunkel asserted 235 divisions exist; 236
theme->binomen pairs are recovered here from the live page (his count and the
page's list do not quite reconcile). Each division has its own
theory, methods, organons, and ideas — i.e. each is a fault-model (P3) for a
whole region of thought, and the list itself is a taxonomy of meta-level
structural concepts.
"""

from __future__ import annotations

DIVISIONS: dict[str, str] = {
    "ABILITIES": "Anystology",
    "ACTS": "Pragmology",
    "ALTERNATIVE HISTORIES": "Nehistorology",
    "ALTERNATIVES": "Allagology",
    "AMBIGUITIES": "Amphibology",
    "ANADESCRIPTIONS": "Anagraphology",
    "ANALOGIES": "Icelology",
    "ANALYSES": "Merismology",
    "ANOMALIES": "Xenology",
    "ANSWERS": "Chresmology",
    "ANTISYZYGIES": "Antisyzygology",
    "APPEARANCES": "Phenology",
    "ASSUMPTIONS": "Lemmology",
    "BADS": "Cacology",
    "BEAUTIES": "Calology",
    "BEHAVIORS": "Ethology",
    "BELIEFS": "Pistology",
    "BINARY BEING": "Catadyology",
    "CAPACITIES": "Hicanology",
    "CAUSES": "Etiology",
    "CHAINS": "Ormology",
    "CHAINS-OF-CONSEQUENCES": "Anyormology",
    "CHANCES": "Tychology",
    "CHANGES": "Tropology",
    "CHAOSES": "Chaology",
    "CIRCUMSTANCES": "Symphorology",
    "CLUSTERS": "Botryology",
    "COEVOLUTIONS": "Syndiatyxology",
    "COMBINATIONS": "Mixology",
    "COMMONALITIES": "Metochology",
    "COMPLEXITIES": "Symplocology",
    "CONCEPTS": "Ennoology",
    "CONFLICTS": "Syrrhagmology",
    "CONNECTIONS": "Desmology",
    "CONSERVATIONS": "Menology",
    "CONTENTS AND PARTS": "Endology",
    "CONTROLS AND GOVERNMENTS": "Cratology",
    "CONTROVERSIES": "Erismology",
    "CONVERGENCES": "Syrrhology",
    "COOPERATIONS": "Synergology",
    "COORDINATE SYSTEMS": "Pantothenology",
    "CO-PROBABILITIES": "Synicology",
    "COROLLARIES": "Diocology",
    "COURSES": "Dromology",
    "CRITERIONS": "Criteriology",
    "CRITICISMS": "Momology",
    "CYCLES": "Nostology",
    "DEBATES AND ARGUMENTS": "Agonology",
    "DECISIONS": "Legology",
    "DEFECTS": "Ateleology",
    "DEFINITIONS": "Orismology",
    "DESCRIPTIONS": "Graphology",
    "DIFFERENCES": "Heterology",
    "DISCOVERIES": "Cyreology",
    "DISEQUILIBRIUMS": "Astatology",
    "DISJUNCTIONS": "Clastology",
    "DISPROOFS": "Catadictology",
    "DISTRIBUTIONS": "Strotology",
    "DIVERGENCES": "Dichology",
    "DOCTRINES": "Dogmology",
    "DOMAINS": "Temenology",
    "ECOLOGIC THINGS": "Ecology",
    "ECONOMIC THINGS": "Oniology",
    "EFFECTS": "Anyology",
    "ELEMENTS": "Stoichiology",
    "EMERGENTS": "Blastology",
    "ENVIRONMENTS": "Periontology",
    "EPOCHES": "Epochology",
    "EQUALITIES": "Isology",
    "EQUILIBRIUMS": "Statology",
    "EQUIVALENCES": "Isaxiology",
    "ERRORS": "Sphalmology",
    "EVALUATIONS": "Crinology",
    "EVENTS": "Synantemology",
    "EXAMPLES": "Tisology",
    "EXCELLENCES": "Aristology",
    "EXCUSES": "Skepsology",
    "EXPECTATIONS": "Elpology",
    "EXPERIENCES": "Idrology",
    "EXPERIMENTS": "Pirology",
    "EXTENSIONS": "Ectatology",
    "EXTREMES": "Malistology",
    "FIELDS": "Gunology",
    "FIRST PRINCIPLES": "Archelogy",
    "FLOWS": "Rheology",
    "FORMS": "Morphology",
    "FUNCTIONS": "Draology",
    "FUNDAMENTALS": "Thelymology",
    "FUTURIBLES": "Mellology",
    "GAMES": "Condacology",
    "GEDANKENEXPERIMENTS": "Phronopirology",
    "GENERALIZATIONS": "Eurynology",
    "GENESES": "Plastology",
    "GOALS": "Balbology",
    "GOODS": "Agathology",
    "GROUPS": "Stellology",
    "HARDEST THINGS": "Mogistology",
    "HETERODOXIES": "Heterodoxology",
    "HIERARCHIES": "Climology",
    "HIGHER REALITIES": "Anohyparology",
    "HISTORIES": "Historology",
    "HYPOTHESES": "Thesology",
    "IDENTITIES": "Tautology",
    "IGNORANCES": "Agnosology",
    "ILLUSIONS": "Apatology",
    "IMAGES": "Idology",
    "IMPLICATIONS": "Semasiology",
    "IMPOSSIBILITIES": "Bymology",
    "INDIVIDUALS": "Idiology",
    "INEQUALITIES": "Anisology",
    "INFINITE COMPLEXITIES": "Apironology",
    "INFINITIES": "Apirology",
    "INFORMATION-THEORETIC AND ENTROPIC THINGS": "Menymology",
    "INSTANCES": "Mericology",
    "INSTRUMENTS": "Labology",
    "INTERACTIONS": "Alleloanyology",
    "INTERDEPENDENCES AND RECIPROCITIES": "Allelology",
    "INTERESTS": "Kedology",
    "INTERPRETATIONS": "Hermenuology",
    "INTER-REPRESENTATIONS": "Alleloschemology",
    "INVENTIONS": "Porizology",
    "INVERSIONS": "Simomology",
    "KNOWLEDGES": "Epistemology",
    "LANGUAGES": "Semonamology",
    "LAWS": "Nomology",
    "LEARNING AND TEACHING": "Didagmology",
    "LEFTOVERS": "Lipsanology",
    "LEVELS": "Blethrology",
    "LIFES": "Biology",
    "LIMITATIONS": "Horology",
    "LOGICAL THINGS": "Synetology",
    "MANIFOLDS": "Choremology",
    "MATHEMATICAL THINGS": "Matology",
    "MATRICES": "Hysterology",
    "MEASUREMENTS": "Metrology",
    "MECHANISMS": "Mechanology",
    "METAPHORS": "Tropeology",
    "METHODS": "Methodology",
    "MINDS": "Noology",
    "MODELS": "Plasmology",
    "MONADS": "Monadology",
    "MONISMS": "Henology",
    "MOTIONS": "Kinology",
    "NAUGHTS": "Anontology",
    "NEEDS": "Chreology",
    "NEGATIONS": "Arnesology",
    "NEGATIVE ANALOGIES": "Anticelology",
    "NEGATIVES": "Hypudamology",
    "NETWORKS": "Dictyology",
    "NETWORKS-OF-CONSEQUENCES": "Anyodictyology",
    "NICHES": "Kenology",
    "NIVEAUS": "Anabathmology",
    "OPPORTUNITIES": "Caerology",
    "OPPOSITES": "Enantiology",
    "ORDERS": "Cybelology",
    "ORIGINS": "Archology",
    "ORTHODOXIES": "Orthodoxology",
    "OUGHTS": "Deontology",
    "PARADIGMS": "Paradigmology",
    "PARADOXES": "Paradoxology",
    "PATHOSES": "Pathology",
    "PATHS": "Hodology",
    "PATTERNS": "Digmology",
    "PERFECTIONS": "Entelology",
    "PERIODICITIES": "Encliology",
    "PERSPECTIVES": "Apopsology",
    "PHENOMENONS": "Enargmology",
    "PLANS": "Medology",
    "POSSIBILITIES": "Prositology",
    "PRACTICES": "Praxology",
    "PREDICTIONS": "Stochology",
    "PREPARATIONS": "Stolizology",
    "PRESENT (THE)": "Artiology",
    "PRINCIPLES": "Axiomology",
    "PROBABILITIES": "Icology",
    "PROBLEMS": "Aporology",
    "PROCESSES": "Sisology",
    "PROJECTIONS": "Sciology",
    "PROOFS": "Dictology",
    "PROPERTIES AND DIMENSIONS": "Usiology",
    "PSYCHOLOGICAL THINGS": "Psychology",
    "PURPOSES": "Bulemology",
    "QUANTITIES": "Posology",
    "QUESTIONS": "Pysmology",
    "RANGES": "Lichology",
    "REACTIONS": "Anabolology",
    "REALMS": "Epirology",
    "RECURSIONS": "Apsology",
    "RELATIONS": "Dochology",
    "RELAXATIONS": "Anetology",
    "REPRESENTATIONS": "Schemology",
    "RESOURCES": "Plutology",
    "ROLES": "Morology",
    "RULES": "Canology",
    "SELF-EFFECTS": "Autanyology",
    "SELF-RELATIONS": "Autodochology",
    "SELF-TRANSCENDENCES": "Autopereology",
    "SERIES": "Irmology",
    "SETS": "Thetology",
    "SHORTCUTS AND THALWEGS": "Brachistology",
    "SIMPLICITIES": "Litology",
    "SIMULATIONS": "Pirohyparology",
    "SOLUTIONS": "Acology",
    "SPACES": "Chorology",
    "SPECTRUMS": "Iridology",
    "SPECULATIONS": "Scemmology",
    "STATES AND CONDITIONS": "Phasology",
    "STORIES": "Enology",
    "STRATEGIES": "Strategology",
    "SUPREMES": "Acrology",
    "SURPRISES": "Adocetology",
    "SYSTEMS": "Systemology",
    "TACTICS": "Apatemology",
    "TAXONS": "Taxology",
    "TERTIUM QUIDS": "Triontology",
    "THEORIES": "Theorology",
    "THINGS (ENTITIES)": "Ontology",
    "THOUGHTS": "Phrontology",
    "TOPOLOGIC THINGS": "Topology",
    "TRANSCENDENCES": "Pereology",
    "TRANSFINITES": "Hyperapirology",
    "TRANSFORMATIONS": "Diaplastology",
    "TYPES": "Typology",
    "ULTIMATES AND ENDS": "Eschatology",
    "ULTRA-FUNDAMENTALS": "Catohyparology",
    "UNCERTAINTIES AND DOUBTS": "Aoristology",
    "UNIFICATIONS (INTEGRATIONS)": "Harmozology",
    "UNIVERSES": "Cosmology",
    "USES": "Chraology",
    "VALUES": "Axiology",
    "VERGENCES": "Chiazology",
    "VIRTUALS": "Mimology",
    "WANTS": "Himerology",
    "WHOLES AND GESTALTS": "Holology",
    "WISDOMS": "Sophology",
    "WORKS": "Ergology",
}


def lens_prompt(theme: str, subject: str) -> str:
    """Render a division as an interrogative lens over a subject (P3 + P14).

    Each Gunkel division asks a different systematic question of any subject.
    """
    field = DIVISIONS.get(theme.upper())
    if field is None:
        raise KeyError(f"unknown division theme: {theme!r}")
    t = theme.lower()
    return (
        f"Apply {field} — the systematic study of {t} — to the subject "
        f"below. Enumerate the {t} present in or implied by it, type them, "
        f"and name the {t} that should exist but are conspicuously absent.\n\n"
        f"Subject: {subject}"
    )
